{"timestamp":"2025-07-17T06:28:49.313368","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-17T06:28:49.314395","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/fetch_cluster.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-17T06:28:49.364232Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T06:28:49.364929Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T06:28:49.365708Z","level":"info","event":"Current task name:get_cluster_id","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T06:28:49.366309Z","level":"info","event":"Dag name:get_databricks_cluster_id","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T06:28:49.379209","level":"info","event":"Connection Retrieved 'databricks_default'","logger":"airflow.hooks.base"}
{"timestamp":"2025-07-17T06:28:49.380194Z","level":"info","event":"General Error: Databricks token is not configured in the connection. Please set the password field with your Databricks personal access token.","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T06:28:49.379678","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AirflowException","exc_value":"Unexpected error: Databricks token is not configured in the connection. Please set the password field with your Databricks personal access token.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/fetch_cluster.py","lineno":87,"name":"get_cluster_id"}],"is_group":false,"exceptions":[]},{"exc_type":"AirflowException","exc_value":"Databricks token is not configured in the connection. Please set the password field with your Databricks personal access token.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/opt/airflow/dags/fetch_cluster.py","lineno":17,"name":"get_cluster_id"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-17T06:28:49.387521Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T06:28:49.388162Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T06:28:49.388565Z","level":"info","event":"Task:<Task(PythonOperator): get_cluster_id>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T06:28:49.388893Z","level":"info","event":"Failure caused by Unexpected error: Databricks token is not configured in the connection. Please set the password field with your Databricks personal access token.","chan":"stdout","logger":"task"}
