{"timestamp":"2025-07-17T05:04:46.243054","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-17T05:04:46.263769","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/trigger_databricks_notebook.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-17T05:04:47.929816Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T05:04:47.932169Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T05:04:47.933630Z","level":"info","event":"Current task name:run_notebook","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T05:04:47.934236Z","level":"info","event":"Dag name:databricks_notebook_trigger","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-17T05:04:48.536407","level":"info","event":"Connection Retrieved 'databricks_default'","logger":"airflow.hooks.base"}
{"timestamp":"2025-07-17T05:04:48.576555","level":"info","event":"Using token auth. For security reasons, please set token in Password field instead of extra","logger":"airflow.task.hooks.airflow.providers.databricks.hooks.databricks.DatabricksHook"}
{"timestamp":"2025-07-17T05:04:49.415576","level":"error","event":"Attempt 1 API Request to Databricks failed with reason: <Future at 0x7ff7e21eee10 state=finished raised SSLError>","logger":"airflow.task.hooks.airflow.providers.databricks.hooks.databricks.DatabricksHook"}
{"timestamp":"2025-07-17T05:04:53.493792","level":"error","event":"Attempt 2 API Request to Databricks failed with reason: <Future at 0x7ff7e1f60a70 state=finished raised SSLError>","logger":"airflow.task.hooks.airflow.providers.databricks.hooks.databricks.DatabricksHook"}
{"timestamp":"2025-07-17T05:05:03.802012","level":"error","event":"Attempt 3 API Request to Databricks failed with reason: <Future at 0x7ff7e1f616d0 state=finished raised ConnectionError>","logger":"airflow.task.hooks.airflow.providers.databricks.hooks.databricks.DatabricksHook"}
{"timestamp":"2025-07-17T05:05:03.802689","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AirflowException","exc_value":"API requests to Databricks failed 3 times. Giving up.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/databricks/operators/databricks.py","lineno":641,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/databricks/hooks/databricks.py","lineno":328,"name":"submit_run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/databricks/hooks/databricks_base.py","lineno":694,"name":"_do_api_call"}],"is_group":false,"exceptions":[]},{"exc_type":"RetryError","exc_value":"RetryError[<Future at 0x7ff7e1f616d0 state=finished raised ConnectionError>]","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/databricks/hooks/databricks_base.py","lineno":672,"name":"_do_api_call"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py","lineno":445,"name":"__iter__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py","lineno":378,"name":"iter"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py","lineno":421,"name":"exc_check"}],"is_group":false,"exceptions":[]},{"exc_type":"ConnectionError","exc_value":"HTTPSConnectionPool(host='dbc-c197be75-7f15.cloud.databricks.com', port=443): Max retries exceeded with url: /api/2.1/jobs/runs/submit (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7ff7e1f61640>: Failed to resolve 'dbc-c197be75-7f15.cloud.databricks.com' ([Errno -3] Temporary failure in name resolution)\"))","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/databricks/hooks/databricks_base.py","lineno":681,"name":"_do_api_call"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/api.py","lineno":115,"name":"post"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/api.py","lineno":59,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py","lineno":589,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py","lineno":703,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":700,"name":"send"}],"is_group":false,"exceptions":[]},{"exc_type":"MaxRetryError","exc_value":"HTTPSConnectionPool(host='dbc-c197be75-7f15.cloud.databricks.com', port=443): Max retries exceeded with url: /api/2.1/jobs/runs/submit (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7ff7e1f61640>: Failed to resolve 'dbc-c197be75-7f15.cloud.databricks.com' ([Errno -3] Temporary failure in name resolution)\"))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":667,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":519,"name":"increment"}],"is_group":false,"exceptions":[]},{"exc_type":"NameResolutionError","exc_value":"<urllib3.connection.HTTPSConnection object at 0x7ff7e1f61640>: Failed to resolve 'dbc-c197be75-7f15.cloud.databricks.com' ([Errno -3] Temporary failure in name resolution)","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":488,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":464,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":1093,"name":"_validate_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":753,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":205,"name":"_new_conn"}],"is_group":false,"exceptions":[]},{"exc_type":"gaierror","exc_value":"[Errno -3] Temporary failure in name resolution","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":198,"name":"_new_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":60,"name":"create_connection"},{"filename":"/usr/local/lib/python3.12/socket.py","lineno":978,"name":"getaddrinfo"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-17T05:05:04.225795","level":"warning","event":"No XCom value found; defaulting to None.","key":"run_page_url","dag_id":"databricks_notebook_trigger","task_id":"run_notebook","run_id":"scheduled__2025-07-17T00:00:00+00:00","map_index":-1,"logger":"task"}
{"timestamp":"2025-07-17T05:05:04.272898","level":"error","event":"Top level error","logger":"task","error_detail":[{"exc_type":"AirflowRuntimeError","exc_value":"API_SERVER_ERROR: {'status_code': 422, 'message': 'Remote server returned validation error', 'detail': {'detail': [{'type': 'missing', 'loc': ['body'], 'msg': 'Field required', 'input': None}]}}","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1302,"name":"main"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1242,"name":"finalize"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":546,"name":"_xcom_push_to_db"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/xcom.py","lineno":116,"name":"_set_xcom_in_db"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/comms.py","lineno":203,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/comms.py","lineno":263,"name":"_get_response"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/comms.py","lineno":250,"name":"_from_frame"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-17T05:05:04.317912Z","level":"warning","event":"Process exited abnormally","exit_code":1,"logger":"task"}
